### ISSUE TITLE
Problem when Install package from github repository

### ISSUE THREAD

**Issue by yizichenguc** [andrewzm/deepspat#2]
Hi,

I was trying to install the package using

`library("devtools")`

`install_github("andrewzm/deepspat")`

However, I got the following error message:

** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'deepspat':
 .onLoad failed in loadNamespace() for 'deepspat', details:
  call: NULL
  error: Your current architecture is 32bit; however, this version of Python was compiled for 64bit.
Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.
Error: loading failed
Execution halted

However I checked my python version called from `reticulate::py_config()`, it's 64bit; I also tried to reinstall miniconda/completely clean R global environment to prevent R reinstall previous global environment according to post [https://forum.greta-stats.org/t/problems-loading-dev-version/209](url), it still gives same error (32bit-error). I wonder is there any additional settings I should do before I run the github install command? Or any suggestions to solve this problem? Thanks!

**Comment by andrewzm** [comment]
Hi,
  I think that problem is coming because reticulate is trying to use 32-bit
python when checking the i386 architecture, nothing to do with deepspat.
This is more likely to happen on Windows machines I think.

1. Go to https://github.com/andrewzm/deepspat/releases/tag/0.1.2 and
download the .tar.gz file
2. In R or RStudio then type
  `install.packages(<path to .tar.gz. file>, type = "source", repos = NULL,
INSTALL_opts="--no-multiarch")`

This should solve the problem.

Best,
Andrew

**Comment by yizichenguc** [comment]
Hi Andrew,

Thanks for your reply! It works!

I've uninstalled all the python on my computer, reinstalled Anaconda and reinstall tensorflow, keras, also install Rtools on my computer, and update to the latest R and Rstudio version.
Also make sure `reticulate` is using tensorflow conda environment.
Then I run `install.packages("~/R/deepspat-0.1.2.tar.gz", repos = NULL, type = "source", INSTALL_opts="--no-multiarch")` , and I successfully installed the package. Not sure which one of them works, so could you please give me an insight about why using `INSTALL_opts="--no-multiarch"` make it work?

Thanks again!

Best,
Yizi

**Comment by andrewzm** [comment]
Not sure I understand your question -- all R packages by default are tested
to work on both 32-bit and 64-bit architectures. For some reason, Python is
not working in 32-bit mode, not sure why. So all we are doing there is
telling the package during installation to not check the 32-bit version
(assuming your machine is 64-bit).

Best,
Andrew

**Comment by yizichenguc** [comment]
Yes that clearly answers my question, thanks!

Best,
Yizi
